### ISSUE TITLE
ReferenceError: URLSearchParams is not defined

### ISSUE THREAD

**Issue by fumeboy** [ZhyMC/chaoxing-xuexitong-autoflush#1]
✔ 请输入超星账户手机号 … 
✔ 请输入账户密码 … 
✔ 已弹出验证码,请在这输入验证码 
登录失败: ReferenceError: URLSearchParams is not defined,请重试!

**Comment by ZhyMC** [comment]
你的node.js版本太低啦，URLSearchParams特性在较新的Node.js版本里存在。旧版本不支持
