### ISSUE TITLE
centos7打不开验证码,显示不是PNG格式,在阿里云运行的centos7linux

### ISSUE THREAD

**Issue by PlayWithSanLei** [ZhyMC/chaoxing-xuexitong-autoflush#14]
![{LE$ IBK{Y{36_A_C5SBOWM](https://user-images.githubusercontent.com/63458338/79695085-3ba46400-82a7-11ea-93b4-655bf6b03c88.png)
怎么解决啊是系统的问题吗

**Comment by litengde** [comment]
阿里云貌似屏蔽了超星。。

**Comment by PlayWithSanLei** [comment]
> 阿里云貌似屏蔽了超星。。

是吗？昨天晚上我换了Ubuntu系统也是收不到图片，然后挂上代理也没有解决这个问题，然后试了下cookie绕过登录，结果进去显示没有课

**Comment by Constellation39** [comment]
我的阿里云轻量应用服务器没有复现这些问题，系统版本是Ubuntu18.04

**Comment by PlayWithSanLei** [comment]
> 我的阿里云轻量应用服务器没有复现这些问题，系统版本是Ubuntu18.04

我的实体机也出现这个问题了，是不是看图软件有问题啊
![sendpix0](https://user-images.githubusercontent.com/63458338/79709243-4afdce80-82f4-11ea-9760-9573499d7aa8.jpg)

**Comment by Constellation39** [comment]
> > 我的阿里云轻量应用服务器没有复现这些问题，系统版本是Ubuntu18.04
> 
> 我的实体机也出现这个问题了，是不是看图软件有问题啊
> ![sendpix0](https://user-images.githubusercontent.com/63458338/79709243-4afdce80-82f4-11ea-9760-9573499d7aa8.jpg)

可以尝试更改为jpg

**Comment by ZhyMC** [comment]
png这个文件格式是我随意写的，因为大部分看图软件都会识别magiccode自动打开一种图片解析器。如果学习通是jpg格式的话，确实应当以jpg格式输出。

**Comment by PlayWithSanLei** [comment]
> png格式文件格式是我随意写的，因为大部分看图软件都识别magiccode自动打开一种图片解析器。如果学习通是jpg格式的话，确实可以以jpg格式输出。

感谢，就是jpg

**Comment by PlayWithSanLei** [comment]
> > > 我的阿里云轻量应用服务器没有复现这些问题，系统版本是Ubuntu18.04
> > 
> > 
> > 我的实体机也出现这个问题了，是不是看图软件有问题啊
> > ![sendpix0](https://user-images.githubusercontent.com/63458338/79709243-4afdce80-82f4-11ea-9760-9573499d7aa8.jpg)
> 
> 可以尝试更改为jpg

感谢老哥就是jpg，我修改一下代码去

**Comment by ZhyMC** [comment]
好，帮我提交一个PR，然后我合并一下

**Comment by PlayWithSanLei** [comment]
> 好，帮我提交一个PR，然后我合并一下

我试试，成了提交

**Comment by Constellation39** [comment]
（已经改了

**Comment by ZhyMC** [comment]
hhhhh

**Comment by PlayWithSanLei** [comment]
> h

不懂就问，老哥我出现这个问题了咋回事求解
![sendpix1](https://user-images.githubusercontent.com/63458338/79710196-d4160500-82f6-11ea-856c-e37ebc95b9f3.jpg)

**Comment by ZhyMC** [comment]
> > h
> 
> 不懂就问，老哥我出现这个问题了咋回事求解
> ![sendpix1](https://user-images.githubusercontent.com/63458338/79710196-d4160500-82f6-11ea-856c-e37ebc95b9f3.jpg)

node版本过低，close issues里面已经有两个人提过了，提问前可以先翻一遍这个。

**Comment by PlayWithSanLei** [comment]
> > > h
> > 
> > 
> > 不懂就问，老哥我出现这个问题了咋回事求解
> > ![sendpix1](https://user-images.githubusercontent.com/63458338/79710196-d4160500-82f6-11ea-856c-e37ebc95b9f3.jpg)
> 
> node版本过低，close issues里面已经有两个人提过了，提问前可以先翻一遍这个。

谢谢，打扰之处还请见谅

**Comment by ZhyMC** [comment]
没事
