### ISSUE TITLE
建议可以支持手动答题，然后把手动答题的答案贡献给服务器

### ISSUE THREAD

**Issue by klenkiven** [ZhyMC/chaoxing-xuexitong-autoflush#15]
就是希望可以通过手动答题的方式，把题目的答案贡献给服务器，然后如果如果服务器答案错误，还可以纠错

**Comment by PlayWithSanLei** [comment]
> 就是希望可以通过手动答题的方式，把过渡的答案贡献给服务器，然后如果如果服务器答案错误，还可以纠错

子龙哥哥想法很不错

**Comment by ZhyMC** [comment]
题库的话，是定义了标准的数据结构的。从而保证从一个学习通账户录得的答案一定能在别的学习通账户上成功作答。手工录入的话这个不太现实，存在污染题库的可能性。

**Comment by ZhyMC** [comment]
如果你要贡献题库，只需要用本程序在你账户上跑一遍即可。

**Comment by klenkiven** [comment]
> > 就是希望可以通过手动答题的方式，把过渡的答案贡献给服务器，然后如果如果服务器答案错误，还可以纠错
> 
> 子龙哥哥想法很不错

被大佬发现

**Comment by klenkiven** [comment]
> 题库的话，是定义了标准的数据结构的。从而保证从一个学习通账户录得的答案一定能在别的学习通账户上成功作答。手工录入的话这个不太现实，存在污染题库的可能性。

如果是在做题过程中呢？比如做的测验题目有10道题目，其中服务器有7道题目。在做的时候，用户可以自己做服务器不存在的题目。最后做完题目，服务器也可以获得正确答案
等到下一位用户使用软件的时候，就可以匹配到正确答案了。
