### ISSUE TITLE
脚本是否在某些情况下没有按照预期运行

### ISSUE THREAD

**Issue by Constellation39** [ZhyMC/chaoxing-xuexitong-autoflush#2]
运行环境为: Ubuntu18.04

脚本运行没有任何异常，单科目运行完成之后查看超星，视频并未标绿。
可以提供的线索是部分视频已经到尾部(差十几秒)但没有完成，另外一部分视频变得可以拖动(可以直接拖到尾)，但是同样没有完成。
![20200323_164104](https://user-images.githubusercontent.com/33367461/77299960-414e6e80-6d28-11ea-8310-a93364067ad6.jpg)

![20200323_164121](https://user-images.githubusercontent.com/33367461/77299915-2ed43500-6d28-11ea-904f-314cb3b8c268.jpg)
![20200323_164133](https://user-images.githubusercontent.com/33367461/77299939-38f63380-6d28-11ea-9b76-ac22f84d695f.jpg)

。

**Comment by ZhyMC** [comment]
问题存在，超星的视频进度report，大概是1分钟一次，而且后台判断视频完成的算法似乎比较严格。目前在大多数情况是可以完成视频的，标志是isPassed在播放器达到90%左右的时候为true，我正在着手于探索一个和超星官方吻合的report频率。

**Comment by Constellation39** [comment]
> 问题存在，超星的视频进度报告，大概是1分钟一次，而且后台判断视频完成的算法近似比较严格。目前在大多数情况下可以完成视频的，标志是isPassed在播放器达到90％左右的时候为true，我正在着手于探索一个和超星官方吻合的报告频率。

好的，感谢付出

**Comment by ZhyMC** [comment]
关于本issue，刚刚做了一点逆向工程，发现学习通的report时间是固定的60秒。
该数值可以在学习通pc版任意一学习卡片的源码里找到reportTimeInterval:60的字样

![report](https://user-images.githubusercontent.com/10328430/77303318-bb352680-6d2d-11ea-95aa-4b302d2d32b0.png)

学习通具体report机制是
①视频开始时，report一个0秒的log
②视频期间，每1分钟report一次进度
③视频结束时，report一个进度为视频总长度的log

而本程序中，是每30秒report一次，猜测学习通后台是以60秒report间隔为算法检测，而且做得很严格，report频率过高过低都不行。

目前正在着手于测试60秒的report频率是否能够稳定完成视频。

**Comment by ZhyMC** [comment]
感谢提问，该问题已被彻底解决，请安装最新版体验使用。 

有关解决该问题的commit：
https://github.com/ZhyMC/chaoxing-xuexitong-autoflush/commit/14e44d4f7e53bd52e652dae15e62a1afc08e1ab0
