### ISSUE TITLE
发现只能刷视频无法答题

### ISSUE THREAD

**Issue by xiaoqianliya** [ZhyMC/chaoxing-xuexitong-autoflush#21]
环境是windows，通过页面的教程搭建的，视频可以正常刷，但是答题无法答题。刷的是慕课，如果一直是跳过答题的话，是否无法完善题库？希望解决下~~~

**Comment by Constellation39** [comment]
https://github.com/ZhyMC/chaoxing-xuexitong-autoflush/issues/17
这个issues里提到了你的问题

**Comment by xiaoqianliya** [comment]
@Constellation39 好，十分感谢你~~~
