### ISSUE TITLE
实时题目数量显示建议更换使用 Shields IO JSON Badge

### ISSUE THREAD

**Issue by Afanyiyu** [ZhyMC/chaoxing-xuexitong-autoflush#22]
建议把这个图片
![quesbankcount](http://quesbank.math.cat:6061/quesbankcount.jpg)
改用 [ShieldsIO](https://shields.io/) 提供的 [JSON Badge](https://shields.io/endpoint) 功能。
- 减少服务器的复杂逻辑（提供JSON即可）
- 图片使用 Shields 生成
- 现在这个图片在GH上了黑色主题且是高分屏的情况下看起来很怪（
![shot](https://user-images.githubusercontent.com/20179549/79894572-3cb8cb00-8438-11ea-806e-d9a1721b2387.png)

**Comment by ZhyMC** [comment]
![count](https://img.shields.io/endpoint?url=https://quesbank.math.cat:6062/bank/getCountInfo)

已采纳

**Comment by Afanyiyu** [comment]
👍
