### ISSUE TITLE
ReferenceError: URLSearchParams is not defined

### ISSUE THREAD

**Issue by 6isixi** [ZhyMC/chaoxing-xuexitong-autoflush#23]
![image](https://s1.ax1x.com/2020/04/23/JUT52n.png)
请问一下这个是什么原因导致的？
环境是Ubuntu
npm版本6.14.4
nodejs版本8.10.0

**Comment by Constellation39** [comment]
https://github.com/ZhyMC/chaoxing-xuexitong-autoflush/issues/1 请升级你的nodejs版本
