### ISSUE TITLE
脚本是否对于多页课程无法处理

### ISSUE THREAD

**Issue by Constellation39** [ZhyMC/chaoxing-xuexitong-autoflush#3]
当一个课程存在多页且视频不在第一页时，脚本似乎不能正确处理
![20200324_082347](https://user-images.githubusercontent.com/33367461/77376163-929f4200-6daa-11ea-9c0a-e0fb40b56755.jpg)
![20200324_082423](https://user-images.githubusercontent.com/33367461/77376161-916e1500-6daa-11ea-9acd-d30563c74fda.jpg)
![20200324_082432](https://user-images.githubusercontent.com/33367461/77376152-8e732480-6daa-11ea-8a69-5d4bcef25566.jpg)

**Comment by ZhyMC** [comment]
我的所有课程中都没有多页的情况发生，所以我没有考虑进这个情况。但这的确是一个要解决的问题，我会working on it，请保持issue开启直到我解决它。

**Comment by ZhyMC** [comment]
更新了新版本，似乎已经解决，可以测试一下。

有关解决该问题的commit：https://github.com/ZhyMC/chaoxing-xuexitong-autoflush/commit/2475747091e1a9701bc61a2611345213b990d87e

**Comment by Constellation39** [comment]
> 更新了新版本，似乎已经解决，可以测试一下。
> 
> 有关解决该问题的提交：[2475747](https://github.com/ZhyMC/chaoxing-xuexitong-autoflush/commit/2475747091e1a9701bc61a2611345213b990d87e)

是的，问题已经解决了
