### ISSUE TITLE
【求教】学习通的视频提交方式是如何获取到的？

### ISSUE THREAD

**Issue by zsmlqlj** [ZhyMC/chaoxing-xuexitong-autoflush#35]
大佬你好，看了你的代码收获颇多，我想请问一下学习通的视频提交方式是如何发现的呢？通过软件抓包吗？网络这方面不太懂，如果有空的话希望能帮我讲讲~

**Comment by ZhyMC** [comment]
现代网站的HTTP请求承载着RPC（远程调用）的功能，所以一般是明文的接口请求，配合调试分析前端的JS代码就可以逆向出这些HTTP接口的用法了，所以实际上是一个较低难度的逆向工程。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhyMC/chaoxing-xuexitong-autoflush"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月19日(星期天) 中午12:51
收件人:&nbsp;"ZhyMC/chaoxing-xuexitong-autoflush"<chaoxing-xuexitong-autoflush@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ZhyMC/chaoxing-xuexitong-autoflush] 【求教】学习通的视频提交方式是如何获取到的？ (#35)





 
大佬你好，看了你的代码收获颇多，我想请问一下学习通的视频提交方式是如何发现的呢？通过软件抓包吗？网络这方面不太懂，如果有空的话希望能帮我讲讲~

**Comment by zsmlqlj** [comment]
谢谢！
