### ISSUE TITLE
续上面的问题

### ISSUE THREAD

**Issue by RavenCri** [ZhyMC/chaoxing-xuexitong-autoflush#44]
出现错误的原因是 两个enc不一样。
![image](https://user-images.githubusercontent.com/39519250/97152215-8b5e6d80-17ab-11eb-88a1-6fc9166dc8e3.png)
点击这个课程会弹出页面并重定向到一个url，这个url会携带一个enc。这个enc参数与mArg里面的enc不一样。我用的是mArg里的enc。所以会提示没有权限，不过我没有好的办法解决这个问题，大佬有时间可以看下。谢谢了

**Comment by OrphanGO** [comment]
同问题，显示无权限访问

**Comment by RavenCri** [comment]
我自己改好了...
