### ISSUE TITLE
centos7 运行报错

### ISSUE THREAD

**Issue by i-never-left-you** [ZhyMC/chaoxing-xuexitong-autoflush#5]
[root@server chaoxing-xuexitong-autoflush]# npm start

> chaoxing@1.0.0 start /root/1/chaoxing-xuexitong-autoflush
> node main.js

版权声明:
作者: Wyatt Zheng
邮箱: yuxon@qq.com

本作品仅提供学习及研究程序原理用途

✔ 请输入超星账户手机号 … 
✔ 请输入账户密码 … 

(提示:若你不是win系统,可以打开目录下的verifycode.png)
✔ 已弹出验证码,请在这输入验证码 … 2052

✔ 请输入视频刷课速率(不填默认为2) … 1
FetchError: request to https://mooc1-1.chaoxing.com/visit/interaction failed, reason: connect ETIMEDOUT 157.185.172.53:443
    at ClientRequest.<anonymous> (/root/1/chaoxing-xuexitong-autoflush/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:321:20)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:321:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  message: 'request to https://mooc1-1.chaoxing.com/visit/interaction failed, reason: connect ETIMEDOUT 157.185.172.53:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}

**Comment by ZhyMC** [comment]
报错提示的很明显，在你计算机的环境，访问https://mooc1-1.chaoxing.com/visit/interaction超时了。

具体是与157.185.172.53进行连接的时候超时，请检查你所在计算机环境的网络问题

**Comment by i-never-left-you** [comment]
PING mooc1-api.chaoxing.com.wswebpic.com (157.185.172.53) 56(84) bytes of data.
64 bytes from 157.185.172.53 (157.185.172.53): icmp_seq=1 ttl=57 time=17.8 ms
64 bytes from 157.185.172.53 (157.185.172.53): icmp_seq=2 ttl=57 time=12.9 ms
64 bytes from 157.185.172.53 (157.185.172.53): icmp_seq=3 ttl=57 time=12.6 ms
64 bytes from 157.185.172.53 (157.185.172.53): icmp_seq=4 ttl=57 time=12.6 ms
64 bytes from 157.185.172.53 (157.185.172.53): icmp_seq=5 ttl=57 time=12.6 ms
64 bytes from 157.185.172.53 (157.185.172.53): icmp_seq=6 ttl=57 time=12.9 ms
64 bytes from 157.185.172.53 (157.185.172.53): icmp_seq=7 ttl=57 time=12.4 ms



..ping了一下..网络好像没什么问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Wyatt"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月9日(星期四) 凌晨0:09
收件人:&nbsp;"ZhyMC/chaoxing-xuexitong-autoflush"<chaoxing-xuexitong-autoflush@noreply.github.com&gt;;
抄送:&nbsp;"sudo"<i.never.left.you@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ZhyMC/chaoxing-xuexitong-autoflush] centos7 运行报错 (#5)





 
报错提示的很明显，在你计算机的环境，访问
 https://mooc1-1.chaoxing.com/visit/interaction
 超时了。
 
具体是与157.185.172.53进行连接的时候超时，请检查你所在计算机环境的网络问题

**Comment by i-never-left-you** [comment]
PING mooc1-api.chaoxing.com.wswebpic.com (157.185.172.53) 56(84) bytes of data.
64 bytes from 157.185.172.53 (157.185.172.53): icmp_seq=1 ttl=57 time=17.8 ms
64 bytes from 157.185.172.53 (157.185.172.53): icmp_seq=2 ttl=57 time=12.9 ms
64 bytes from 157.185.172.53 (157.185.172.53): icmp_seq=3 ttl=57 time=12.6 ms
64 bytes from 157.185.172.53 (157.185.172.53): icmp_seq=4 ttl=57 time=12.6 ms
64 bytes from 157.185.172.53 (157.185.172.53): icmp_seq=5 ttl=57 time=12.6 ms
64 bytes from 157.185.172.53 (157.185.172.53): icmp_seq=6 ttl=57 time=12.9 ms
64 bytes from 157.185.172.53 (157.185.172.53): icmp_seq=7 ttl=57 time=12.4 ms



..ping了一下..网络好像没什么问题




刚刚试了一下 没问题了...昨天晚上可能网络不太好.不好意思.打扰了


------------------ 原始邮件 ------------------
发件人:&nbsp;"Wyatt"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月9日(星期四) 凌晨0:09
收件人:&nbsp;"ZhyMC/chaoxing-xuexitong-autoflush"<chaoxing-xuexitong-autoflush@noreply.github.com&gt;;
抄送:&nbsp;"sudo"<i.never.left.you@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ZhyMC/chaoxing-xuexitong-autoflush] centos7 运行报错 (#5)





 
报错提示的很明显，在你计算机的环境，访问
 https://mooc1-1.chaoxing.com/visit/interaction
 超时了。
 
具体是与157.185.172.53进行连接的时候超时，请检查你所在计算机环境的网络问题

**Comment by ZhyMC** [comment]
好的
