### ISSUE TITLE
linux登陆提示 登录失败: ReferenceError: URLSearchParams is not defined,请重试!

### ISSUE THREAD

**Issue by Yan9z** [ZhyMC/chaoxing-xuexitong-autoflush#6]
linux登陆提示 登录失败: ReferenceError: URLSearchParams is not defined,请重试!
![image](https://user-images.githubusercontent.com/42397434/79061354-17062600-7cc2-11ea-8207-24e7da2d8754.png)

**Comment by ZhyMC** [comment]
https://github.com/ZhyMC/chaoxing-xuexitong-autoflush/issues/1
请参考该issue
